repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]
        files: (package\.json|tsconfig\.json)$
        types: [file]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff-format
        name: python format
      - id: ruff
        alias: ruff-check
        name: python lint
        args: [--fix]

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      # lint fetches schemas online at each call, deactivate for now
      - id: taplo-lint
