name: Set up rye
runs:
  using: 'composite'
  steps:
    # now install rye and sync the dependencies
    - uses: eifinger/setup-rye@v4
      with:
        version: "0.42.0"
        enable-cache: false
    - run: rye sync
      shell: ${{ runner.os == 'Windows' && 'powershell' || 'bash' }}
