name: Release
on:
  push:
    # tags:
    #   - '[0-9].[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish to PyPi
    # if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup_rye
      - name: Build package
        run: rye build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
