name: Release
on:
  push:
    # tags:
    #   - '[0-9].[0-9]+.[0-9]+'

jobs:
  publish:
    name: Publish to PyPi
    # if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Build and publish
        run: flit publish
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI }}
