name: Release
on:
  push:
    # tags:
    #   - '[0-9].[0-9]+.[0-9]+'

permissions:
    id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    contents: read

jobs:
  publish:
    name: Publish to PyPi
    # if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup_rye
      - name: Build package
        run: rye build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: sphinx-codelinks/dist/
